# Generated by Django 4.0.1 on 2022-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(default=0)),
                ('funit', models.CharField(max_length=255)),
                ('amplitude', models.FloatField(default=0)),
                ('aunit', models.CharField(max_length=255)),
                ('sequence', models.CharField(max_length=255)),
                ('trace', models.IntegerField(default=0)),
                ('r', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('lab', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['trace'],
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
